---
title: "R para analise espacial"
description: |
  Links interessantes para aprendizagem de R como ferramenta de tratamento da informacao espacial
author: Renata Oliveira
date: 08-20-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
:::justa
A comunidade acadêmica tem caminhado para abertura de licença de uso e reprodução de material didático, bases de dados, e conteúdo que pode ajudar a construção de competências e a aprendizagem em diferentes contextos. A universalização da informação é responsabilidade do docente que acredita na mudança por meio da educação. A Internet tem possibilitado tanto a publicação como o acesso a diferentes formas de apresentação de conteúdo que, em conjunto, contribuem para a formação de profissionais e outros acadêmicos. Infelizmente vivemos em um país onde a desigualdade ainda diferencia as pessoas, também em relação ao acesso à Internet. Nesse contexto, a abertura pública de conteúdo faz-se ainda mais necessária e eficaz, contribuindo para pequenas ações que podem mudar o mundo. 

Trago aqui algumas dicas de sites, livros e material para implementações práticas que foram generosamente publicados por seus autores. 

### Em português



### Em inglês

[Introduction to visualising spatial data in R by Robin Lovelace (R.Lovelace@leeds.ac.uk), James Cheshire, Rachel Oldroyd and others](https://cran.r-project.org/doc/contrib/intro-spatial-rl.pdf)

[Geocomputation with R by Robin Lovelace, Jakub Nowosad, Jannes Muenchow](https://geocompr.robinlovelace.net/)

[Geospatial Analysis in R by Major David Beskow](http://data-analytics.net/cep/Schedule_files/geospatial.html)

[Language Technology and Data Analysis Laboratory (LADAL) of the School of Languages and Cultures at the University of Queensland](https://slcladal.github.io/index.html)

[Intro to GIS and Spatial Analysis by Manuel Gimond](https://mgimond.github.io/Spatial/index.html)

[Mapping Spatial Data in R by Hautahi Kingi](https://hautahi.com/rmaps)

[Introduction to GIS with R by Jesse Sadler](https://www.jessesadler.com/post/gis-with-r-intro/)

[Spatial Data in R: New Directions by Edzer Pebesma](https://edzer.github.io/UseR2017/)

[Spatio-Temporal Statistics with R by Christopher K. Wikle, Andrew Zammit-Mangion, and Noel Cressie](https://spacetimewithr.org/)

[Use R! by Robert Gentleman Kurt Hornik Giovanni Parmigiani](http://gis.humboldt.edu/OLM/r/Spatial%20Analysis%20With%20R.pdf)

[Applied Spatial Data Analysis with R by Roger S. Bivand, Edzer Pebesma and Virgilio Gómez-Rubio](https://link.springer.com/content/pdf/10.1007%2F978-1-4614-7618-4.pdf)

[Geospatial Data in R and beyond by Barry Rowlingson](https://www.maths.lancs.ac.uk/~rowlings/Teaching/UseR2012/cheatsheet.html)

[spatial-analyst.net by Tomislav Hengl](spatial-analyst.net)

[Introduction to Mapping and Spatial Analysis with R by Branner Earth Sciences Library - Teaching Corner](https://cengel.github.io/rspatial/)

[Mapping Spatial Data in R by Hautahi Kingi](https://hautahi.com/rmaps)

[Processing R Provider by North Road and Jan Caha](https://north-road.github.io/qgis-processing-r/)

[Spatial Data Science with R by Robert J. Hijmans](https://rspatial.org/)

[Introduction to GIS with R by Jesse Sadler](https://www.jessesadler.com/post/gis-with-r-intro/)

[R Spatial software blogs and ideas by Edzer Pebesma](https://www.r-spatial.org/)

[Spatial Data Science by Edzer Pebesma, Roger Bivand](https://keen-swartz-3146c4.netlify.app/)

:::

